stages:
- name: Build
  steps:
  - runScriptConfig:
      image: node:9.2.1-alpine
      shellScript: |-
        npm install -g cnpm --registry=https://registry.npm.taobao.org
        cnpm install
        cnpm run build
- name: publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: xiaozao-mi:${CICD_EXECUTION_SEQUENCE}
      registry: 127.0.0.1:34414
- name: Run
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
notification:
  recipients:
  - recipient: http://10.35.19.232:31838/robot/send?access_token=ea93ed9253488574e8a974891cb4ede1b1e8ee07444b058c1ebd7982f5b76287
    notifier: c-kzx7h:n-2tmfs
  condition:
  - Success
  - Changed
  - Failed
