stages:
- name: Build
  steps:
  - runScriptConfig:
      image: node:8.9-alpine
      shellScript: "npm install \nnpm run build"
- name: publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: xiaozao:${CICD_EXECUTION_SEQUENCE}
      registry: 127.0.0.1:34414
- name: Run
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
notification: {}
